/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
 *
 * Generated on: 06-Dec-2018 05:12:25
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 131
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2012b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int Filter_Laenge = 131;
const short Filter[131] = {
     -218,    -41,    -29,     -5,     27,     64,    101,    131,    150,
      152,    136,    102,     54,     -3,    -62,   -114,   -152,   -171,
     -168,   -146,   -108,    -62,    -15,     22,     45,     50,     37,
       12,    -17,    -40,    -45,    -26,     23,    100,    195,    295,
      382,    435,    436,    373,    240,     45,   -196,   -456,   -702,
     -898,  -1010,  -1012,   -889,   -645,   -297,    121,    562,    973,
     1302,   1502,   1542,   1406,   1104,    665,    135,   -426,   -952,
    -1380,  -1660,  31011,  -1660,  -1380,   -952,   -426,    135,    665,
     1104,   1406,   1542,   1502,   1302,    973,    562,    121,   -297,
     -645,   -889,  -1012,  -1010,   -898,   -702,   -456,   -196,     45,
      240,    373,    436,    435,    382,    295,    195,    100,     23,
      -26,    -45,    -40,    -17,     12,     37,     50,     45,     22,
      -15,    -62,   -108,   -146,   -168,   -171,   -152,   -114,    -62,
       -3,     54,    102,    136,    152,    150,    131,    101,     64,
       27,     -5,    -29,    -41,   -218
};
